title: Moch. Aril Indra Permana # your name (or website title) here
logo: "/images/1641316559613.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  As a Senior Data Scientist with over 6 years of experience across fintech, e-commerce, and telecommunications sectors, I specialize in developing and deploying cutting-edge machine learning models and advanced analytics solutions. My expertise spans Python, SQL, big data technologies, and cloud platforms, with a focus on NLP, computer vision, and OCR. A physics graduate from Padjadjaran University, I bring a rigorous analytical approach to solving complex business problems. My career highlights include optimizing fraud detection systems, automating financial processes, and implementing OCR solutions that significantly improved operational efficiency. I'm passionate about leveraging data to drive business value and continuously expanding my skills in the rapidly evolving field of data science.
  <br><br>
  <a href="https://www.linkedin.com/in/moch-aril-indra-permana-52887b138/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
